name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libgdk-pixbuf2.0-dev librust-atk-dev libcairo2-dev libpango1.0-dev libgtk-3-dev libxdo-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
